language: php
php:
- 7.0

script:
# Override default Travis script action [phpunit]
- php -l *.php

branches:
  only:
  # Enable Travis hook on tags (there is regular expression for semver tag)*
  - "/\\d\\.\\d\\.\\d/"

# Enable Travis deployment
deploy:
  # Use script as a deployment tool
  provider: script
  script: deploy/deploy.sh
  # Restrict deployment only for tags
  on:
    tags: true

# Deployment script requires few enviromnet variables
env:
  global:
  - SVN_REPOSITORY=http://plugins.svn.wordpress.org/resoc-social-editor/
  - secure: RRNDYOetjT9mzUCiD9LmZAfbf1DiJNyDa/NdBxUiLpieL+x0Vl9qG3uKcDN1+Yh8ZU0SrEqdhYG1VYYc5Eh52euFmrr9ORrkOhRugIQKeXwzeosWmG8l/RA8dL+5XM8eJGjAS2p01ItdvM0mg/cSEOgougsTGcTnVe67yj9MVuRM0T38ZNDAgBmj8CRYg0Hz9QmD3l+i7btfEVbb5Yup6p2urmjtuuW9CAMGQ+WpdesB0skO4YQ8rHc09Njc29GcmchDbXvwOGlpQ7PcmzSXHGG9JGM1Ryl/71zGIjEWMphzTWzyVr9FDgKdBNzNOaDZG/iyNh2x8YB7IWIiFma6TTAklUdGg3OQ0gArljUARhoVkar2EPSX6QwEqwQVranZXDpM3wJ72m/uUGpjfNoziMc/MHEFCAQnQ2kPc9rXWBIJ5DsbJ3IGQRPE6/VpADqLYa0m0nI05cF0mUqhYsbHtmcYjfg7UuyK/35lGBxfVPGTJslLgw1+x83pfwyrpI17oBo9Wb8fewR0gI7jJMOYi/y4vofXZRFjK5XqMQLpEdBJgwsxx7xdnH5v/nUsXaFqHskLo1YU62eh+rspzUHv/Sd/hlvAgHotkte6JIcJXPMrc5xEewgt5IuE9gchR8s9QsDPjoX97MRaXIg6Do/Rfagy/fg2GWhnpg263XmOzQw=
  - secure: xDUxWG9tBhgpaQNmQDNZqbXjWoYnOWe5/2INbaG0Kj0pwPg93m7n84wKzc1HEYpSFTbg/dRs9Gm8JDERvEp6tu5MORg92gB/rIn2z8/y8vn52tCh4sGpjFVIkttbBMqS/F/OOwxlt8SBfVRks8P8lUASaE/xSK0i4cuneewjMsvhQstedkAT4ryOmrJVO3gdsFmf1gwGEBxuhvUvHYbEBH0S3QVoqOWeB4hWlJajGhIrboxGx3lHDEYFasusN3rjOK4NfV0fu0zt2cS0lj5503DBcitAhx2VoS1949SVyyo5l5AFW8TrxplsMHQMs0+pVxvz0H7/RpcqIl4sCKiqWJEkgyz0kS7i1/lC4L4ljQixM7O8mP4JfsOHfXNRfpnzuuRkpDrFaJnuW/TwShR8X1cbzRDtR04Gu+mB9/Tsds4eaGwVjFghpX4pg6yKGpOL4ODg1dW5AZx/cJAJ4o/xK/FZPFJ2UZjbeAKfJJAudNZw7MbgbGayYc9mE/5JkU4dWxcVklWl/mMa9bmeM5+sDW4QupqZlHjgaj1Pivz9+8oLraMUxsM6EtWksBqkX0lqG6PGL6yzxE4gTMfDeboaRp+wIZA+aoyCY0gB+gceZNyTJFYsqyLEsMYOUCxw2eAOTAcstAbNVOCu2RazJRuU1fwwfdzf6bIqvA02YxAYqQU=
